version: '3.8'

services:
  api:
    build: .
    container_name: influverse-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: influverse-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
